### ISSUE TITLE
Can open 'Reference Ontology of Trustworthiness Requirements.vpp' (null pointer exception)

### ISSUE THREAD

**Issue by nherbaut** [unibz-core/trustworthiness-requirements-ontology#1]
Hello @glendacma , 

thanks for your research,

I'm trying to open the 'Reference Ontology of Trustworthiness Requirements.vpp' file with a fresh install of VisualParadigm 17.1 with the latest version of OntoUML 0.5.3, but the program crashes with a null pointer exception. 
I've notified Visual Paradigm for the issue, but I wonder if it could be possible in the mean time to provide an updated version of the file that would run on the latest VP release OR tell me which VP version could open the file OR provide the ontology as an OWL file.

Many thanks.

**Comment by glendacma** [comment]
Dear Nicolas,

You can find the implementation of ROT in OWL in https://github.com/unibz-core/trust-ontology

 

Note that, since this implementation, we have developed ROT even further:

 

Amaral, G., Sales, T. P., Guizzardi, G. (2022). Ontological Foundations for Trust Dynamics: The Case of Central Bank Digital Currency Ecosystems. In: Research Challenges in Information Science. RCIS 2022.

 

Amaral, G. (2022). An Ontology Network in Finance and Economics: Money, Trust, Value, Risk and Economic Exchanges. PhD Thesis. Free University of Bozen-Bolzano, Italy. 

 

Baratella, R., Amaral, G., Sales, T. P., Guizzardi, R., & Guizzardi, G. The Many Facets of Trust. In: International Conference on Formal Ontology in Information Systems (FOIS 2023)

Best regards,Glenda

    Em sexta-feira, 27 de outubro de 2023 13:57:01 GMT+1, Nicolas Herbaut ***@***.***> escreveu:  
 
 


Hello @glendacma ,

thanks for your research,

I'm trying to open the 'Reference Ontology of Trustworthiness Requirements.vpp' file with a fresh install of VisualParadigm 17.1 with the latest version of OntoUML 0.5.3, but the program crashes with a null pointer exception.
I've notified Visual Paradigm for the issue, but I wonder if it could be possible in the mean time to provide an updated version of the file that would run on the latest VP release OR tell me which VP version could open the file OR provide the ontology as an OWL file.

Many thanks.

**Comment by nherbaut** [comment]
awesome, both files can be opened with both Protegé and Visual Paradigm, many thanks!

Since your paper links to this repo, you should consider adding a link to the other resources in the readme.md so that other may use the updated material directly.

Best,
